#!/bin/bash
# create log file
chmod +x /data/ACWH_Switch/services/auto_switch/run
chmod +x /data/ACWH_Switch/services/auto_switch/log/run
chmod 777 /data/ACWH_Switch/auto_switch.py

packageLogFile="/data/ACWH_Switch/log"

# everything done in HelperResources which never returns here !!!

standardPromptAndActions='yes'

#### following line incorporates helper resources into this script
source "/data/SetupHelper/HelperResources/IncludeHelpers"
#### end of lines to include helper resources
